// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzeuqhojxaxlbzclwdiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ZXVxaG9qeGF4bGJ6Y2x3ZGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjI0MjUsImV4cCI6MjA2MDQ5ODQyNX0.s70YEwHa5y82rzVtO7eR0vBJfGXTVVX1rOLU_Qpsbfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);